INSERT INTO categoria (nome) VALUES
                                 ('Ficção Científica'),
                                 ('Fantasia'),
                                 ('Romance'),
                                 ('Suspense'),
                                 ('Terror'),
                                 ('Aventura'),
                                 ('História'),
                                 ('Biografia'),
                                 ('Autoajuda'),
                                 ('Poesia'),
                                 ('Drama'),
                                 ('Humor'),
                                 ('Infantil'),
                                 ('Didático'),
                                 ('Tecnologia'),
                                 ('Programação'),
                                 ('Ciência'),
                                 ('Filosofia'),
                                 ('Psicologia'),
                                 ('Sociologia'),
                                 ('Religião'),
                                 ('Negócios'),
                                 ('Administração'),
                                 ('Direito'),
                                 ('Artes');