
    create table autor (
        deleted boolean not null,
        id varchar(255) not null,
        nacionalidade varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    );

    create table autor_escreve_livro (
        fk_autor_oplid varchar(255) not null,
        fk_livro_isbn varchar(255) not null,
        primary key (fk_autor_oplid, fk_livro_isbn)
    );

    create table biblioteca (
        bairro varchar(255) not null,
        cep varchar(255) not null,
        cidade varchar(255) not null,
        cnpj varchar(255) not null,
        complemento varchar(255) not null,
        estado varchar(255) not null,
        nome varchar(255) not null,
        numero varchar(255) not null,
        país varchar(255) not null,
        rua varchar(255) not null,
        primary key (cnpj)
    );

    create table categoria (
        id bigint generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    );

    create table editora (
        deleted boolean,
        razao_social varchar(255) not null,
        primary key (razao_social)
    );

    create table endereco_editora (
        id bigint generated by default as identity,
        bairro varchar(255) not null,
        cep varchar(255) not null,
        cidade varchar(255) not null,
        complemento varchar(255) not null,
        estado varchar(255) not null,
        fk_editora_razao_social varchar(255) not null,
        numero varchar(255) not null,
        pais varchar(255) not null,
        rua varchar(255) not null,
        primary key (id)
    );

    create table exemplar (
        proprio boolean not null,
        numero_exemplar bigint not null,
        fk_livro_oplid varchar(255) not null,
        isbn varchar(255) not null,
        status varchar(255) not null check (status in ('DISPONIVEL','EMPRESTADO','RESERVADO','MANUTENCAO')),
        primary key (numero_exemplar, isbn)
    );

    create table livro (
        deleted boolean not null,
        disponiveis smallint not null,
        quantidade smallint not null,
        ano_publicacao varchar(255) not null,
        fk_biblioteca_cnpj varchar(255) not null,
        fk_editora_razao_social varchar(255) not null,
        idioma varchar(255) not null,
        imagem_url varchar(255) not null,
        isbn varchar(255) not null,
        sinopse varchar(255) not null,
        titulo varchar(255) not null,
        primary key (isbn)
    );

    create table livro_pertence_categoria (
        fk_categoria_id bigint not null,
        fk_livro_isbn varchar(255) not null,
        primary key (fk_categoria_id, fk_livro_isbn)
    );

    create table usuario (
        data_nasc date not null,
        deleted boolean,
        senha varchar(60) not null,
        cpf varchar(255) not null,
        email varchar(255) not null unique,
        pri_nome varchar(255),
        rg varchar(255) not null unique,
        sob_nome varchar(255),
        primary key (cpf)
    );

    create table usuario_emprestimo_exemplar (
        data_devolucao timestamp(6) not null,
        data_devolucao_prevista timestamp(6) not null,
        data_emprestimo timestamp(6) not null,
        fk_exemplar_numero_exemplar bigint not null,
        id bigint generated by default as identity,
        fk_livro_isbn varchar(255) not null,
        fk_usuario_cpf varchar(255) not null,
        livro_isbn varchar(255) not null,
        primary key (id)
    );

    create table usuario_reserva_livro (
        posicao_fila smallint not null,
        data_reserva timestamp(6) not null,
        id bigint generated by default as identity,
        fk_livro_isbn varchar(255) not null,
        fk_usuario_oplid varchar(255) not null,
        status varchar(255) not null check (status in ('PENDENTE','DISPONIVEL','CANCELADA','CONCLUIDA')),
        primary key (id)
    );

    alter table if exists autor_escreve_livro 
       add constraint FK91sr652x7uoj7xtsuexf2713h 
       foreign key (fk_autor_oplid) 
       references autor;

    alter table if exists autor_escreve_livro 
       add constraint FK4x8d9s9ninu751flkaddvut66 
       foreign key (fk_livro_isbn) 
       references livro;

    alter table if exists endereco_editora 
       add constraint FKce9cs5g15ay72ldol8oxgy00x 
       foreign key (fk_editora_razao_social) 
       references editora;

    alter table if exists exemplar 
       add constraint FKjj1mwl2prfllsiurxdjbtrgua 
       foreign key (fk_livro_oplid) 
       references livro;

    alter table if exists livro 
       add constraint FKgfmrh7icg1vp1wy52yw0pqlux 
       foreign key (fk_biblioteca_cnpj) 
       references biblioteca;

    alter table if exists livro 
       add constraint FKhbrgfugbh16le4fdpb7e31m8x 
       foreign key (fk_editora_razao_social) 
       references editora;

    alter table if exists livro_pertence_categoria 
       add constraint FKawn07s420vvf5hx03jd9rakgj 
       foreign key (fk_categoria_id) 
       references categoria;

    alter table if exists livro_pertence_categoria 
       add constraint FKpulg6985lvfs1oqp9xowdupn2 
       foreign key (fk_livro_isbn) 
       references livro;

    alter table if exists usuario_emprestimo_exemplar 
       add constraint FKbvus1sqk682nhc7kin3clrsf4 
       foreign key (fk_exemplar_numero_exemplar, fk_livro_isbn) 
       references exemplar;

    alter table if exists usuario_emprestimo_exemplar 
       add constraint FKaqa1l76seuvu30x2g07ywj33o 
       foreign key (fk_usuario_cpf) 
       references usuario;

    alter table if exists usuario_reserva_livro 
       add constraint FK1lublwktxbkkpmo2hp830xf9 
       foreign key (fk_livro_isbn) 
       references livro;

    alter table if exists usuario_reserva_livro 
       add constraint FKdjfv6bhs1t69u2u5tslqmpbmm 
       foreign key (fk_usuario_oplid) 
       references usuario;
