insert into autor (deleted, id, nacionalidade, nome) values
                                                         (false, 'OL23919A', 'UNITED_KINGDOM', 'Jane Austen'),
                                                         (false, 'OL2162280A', 'UNITED_KINGDOM', 'George Orwell'),
                                                         (false, 'OL26320A', 'UNITED_STATES', 'F. Scott Fitzgerald'),
                                                         (false, 'OL262283A', 'UNITED_STATES', 'J.D. Salinger'),
                                                         (false, 'OL25712A', 'UNITED_STATES', 'Cormac McCarthy'),
                                                         (false, 'OL139435A', 'AFGHANISTAN', 'Khaled Hosseini'),
                                                         (false, 'OL34184A', 'UNITED_KINGDOM', 'Aldous Huxley'),
                                                         (false, 'OL21806A', 'COLOMBIA', 'Gabriel García Márquez'),
                                                         (false, 'OL22098A', 'GREECE', 'Homer'),
                                                         (false, 'OL34185A', 'RUSSIA', 'Fyodor Dostoevsky'),
                                                         (false, 'OL2162290A', 'UNITED_STATES', 'Ray Bradbury'),
                                                         (false, 'OL26321A', 'UNITED_STATES', 'Harper Lee'),
                                                         (false, 'OL139436A', 'UNITED_STATES', 'Toni Morrison'),
                                                         (false, 'OL34186A', 'UNITED_STATES', 'William Golding'),
                                                         (false, 'OL2162300A', 'UNITED_KINGDOM', 'William Shakespeare'),
                                                         (false, 'OL26322A', 'UNITED_STATES', 'J.K. Rowling'),
                                                         (false, 'OL139437A', 'SWEDEN', 'Stieg Larsson'),
                                                         (false, 'OL34187A', 'FRANCE', 'Albert Camus'),
                                                         (false, 'OL2162310A', 'ITALY', 'Dante Alighieri'),
                                                         (false, 'OL26323A', 'UNITED_STATES', 'Herman Melville'),
                                                         (false, 'OL2162320A', 'BRAZIL', 'Paulo Coelho'),
                                                         (false, 'OL139438A', 'UNITED_KINGDOM', 'Charlotte Brontë'),
                                                         (false, 'OL34188A', 'UNITED_STATES', 'Mark Twain'),
                                                         (false, 'OL2162330A', 'GERMANY', 'Johann Wolfgang von Goethe'),
                                                         (false, 'OL26324A', 'RUSSIA', 'Leo Tolstoy');
