-- Script de inserção de livros baseado nos autores cadastrados
-- Cada autor tem pelo menos 2 livros

-- Jane Austen (OL23919A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 5, 5, '1813', '63.025.530/0062‑26', 'Penguin Editora', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg', '9780141439518', 'Um romance sobre Elizabeth Bennet e Sr. Darcy, explorando temas de amor, orgulho e classe social na Inglaterra da Regencia.', 'Orgulho e Preconceito'),
                                                                                                                                                                 (false, 5, 5, '1815', '63.025.530/0062‑26', 'Penguin Editora', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780141439686-L.jpg', '9780141439686', 'Um romance sobre Emma Woodhouse, uma jovem que adora fazer casamentos para outros, mas enfrenta complicacoes romanticas proprias.', 'Emma'),
                                                                                                                                                                 (false, 5, 5, '1811', '63.025.530/0062‑26', 'Penguin Editora', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780141439662-L.jpg', '9780141439662', 'A historia das irmas Dashwood buscando amor e seguranca apos a morte de seu pai, contrastando razao e sensibilidade.', 'Razao e Sensibilidade');

-- George Orwell (OL2162280A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 10, 10, '1949', '63.025.530/0062‑26', 'Companhia das Letras', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg', '9780451524935', 'Um romance distopico ambientado na Oceania totalitaria onde o Grande Irmao observa tudo e a individualidade e esmagada.', '1984'),
                                                                                                                                                                 (false, 10, 10, '1945', '63.025.530/0062‑26', 'Companhia das Letras', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780451526342-L.jpg', '9780451526342', 'Uma alegoria satirica do totalitarismo sovietico onde animais de fazenda se rebelam contra seu fazendeiro humano.', 'A Revolucao dos Bichos');

-- F. Scott Fitzgerald (OL26320A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 2, 2, '1925', '63.025.530/0062‑26', 'Scribner', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg', '9780743273565', 'A historia de Jay Gatsby e sua busca obsessiva por Daisy Buchanan, retratando a Era do Jazz e o Sonho Americano.', 'O Grande Gatsby'),
                                                                                                                                                                 (false, 2, 2, '1934', '63.025.530/0062‑26', 'Scribner', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780684801544-L.jpg', '9780684801544', 'Um romance semi-autobiografico seguindo Dick Diver, um psiquiatra que se casa com uma paciente rica na Europa pos-Primeira Guerra.', 'Suave e a Noite');

-- J.D. Salinger (OL262283A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 10, 10, '1951', '63.025.530/0062‑26', 'Little Brown', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg', '9780316769488', 'Holden Caulfield narra suas experiencias em Nova York apos ser expulso da escola preparatoria.', 'O Apanhador no Campo de Centeio'),
                                                                                                                                                                 (false, 10, 10, '1961', '63.025.530/0062‑26', 'Little Brown', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780316769174-L.jpg', '9780316769174', 'Uma colecao de quatro historias interligadas sobre a familia Glass, explorando temas de espiritualidade e identidade.', 'Franny e Zooey');

-- Cormac McCarthy (OL25712A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 6, 6, '2006', '63.025.530/0062‑26', 'Vintage Books', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780307387899-L.jpg', '9780307387899', 'Um conto pos-apocaliptico de um pai e filho viajando por uma America devastada.', 'A Estrada'),
                                                                                                                                                                 (false, 6, 6, '1992', '63.025.530/0062‑26', 'Vintage Books', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780679744399-L.jpg', '9780679744399', 'Um epico western seguindo um adolescente que se junta a um bando de cacadores de escalpos indigenas na fronteira Texas-Mexico dos anos 1850.', 'Meridiano de Sangue');

-- Khaled Hosseini (OL139435A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 6, 6, '2003', '63.025.530/0062‑26', 'Riverhead Books', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg', '9781594631931', 'Uma historia de amizade e traicao entre dois garotos no Afeganistao, abrangendo decadas de tumulto.', 'O Cacador de Pipas'),
                                                                                                                                                                 (false, 6, 6, '2007', '63.025.530/0062‑26', 'Riverhead Books', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9781594489501-L.jpg', '9781594489501', 'Duas mulheres de geracoes e origens diferentes tem suas vidas entrelacadas no Afeganistao devastado pela guerra.', 'Mil Sois Esplendidos');

-- Aldous Huxley (OL34184A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 2, 2, '1932', '63.025.530/0062‑26', 'Harper Perennial', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg', '9780060850524', 'Uma visao distopica de uma sociedade futurista onde humanos sao geneticamente modificados e controlados atraves do prazer.', 'Admiravel Mundo Novo'),
                                                                                                                                                                 (false, 2, 2, '1954', '63.025.530/0062‑26', 'Harper Perennial', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780060595180-L.jpg', '9780060595180', 'Um ensaio explorando as experiencias de Huxley com mescalina e a natureza da consciencia e percepcao.', 'As Portas da Percepcao');

-- Gabriel García Márquez (OL21806A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 2, 2, '1967', '63.025.530/0062‑26', 'Harper Perennial', 'SPANISH', 'https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg', '9780060883287', 'A historia multigeracional da familia Buendia na cidade ficticia de Macondo, uma obra-prima do realismo magico.', 'Cem Anos de Solidao'),
                                                                                                                                                                 (false, 2, 2, '1985', '63.025.530/0062‑26', 'Vintage Books', 'SPANISH', 'https://covers.openlibrary.org/b/isbn/9780307389732-L.jpg', '9780307389732', 'Um conto de amor apaixonado e duradouro entre Florentino Ariza e Fermina Daza ao longo de mais de cinquenta anos.', 'O Amor nos Tempos do Colera');

-- Homer (OL22098A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 3, 3, '-800', '63.025.530/0062‑26', 'Penguin Classics', 'GREEK', 'https://covers.openlibrary.org/b/isbn/9780140268867-L.jpg', '9780140268867', 'Um poema epico sobre a jornada de dez anos de Odisseu retornando para casa apos a Guerra de Troia.', 'Odisseia'),
                                                                                                                                                                 (false, 3, 3, '-750', '63.025.530/0062‑26', 'Penguin Classics', 'GREEK', 'https://covers.openlibrary.org/b/isbn/9780140275360-L.jpg', '9780140275360', 'Um poema epico ambientado durante a Guerra de Troia, focando na ira de Aquiles e suas consequencias.', 'Iliada');

-- Fyodor Dostoevsky (OL34185A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 16, 16, '1866', '63.025.530/0062‑26', 'Penguin Classics', 'RUSSIAN', 'https://covers.openlibrary.org/b/isbn/9780143058144-L.jpg', '9780143058144', 'Um drama psicologico sobre Raskolnikov, um estudante que comete assassinato e luta com culpa e redencao.', 'Crime e Castigo'),
                                                                                                                                                                 (false, 16, 16, '1880', '63.025.530/0062‑26', 'Penguin Classics', 'RUSSIAN', 'https://covers.openlibrary.org/b/isbn/9780374528379-L.jpg', '9780374528379', 'Um romance filosofico explorando fe, duvida e moralidade atraves da historia da familia Karamazov.', 'Os Irmaos Karamazov');

-- Ray Bradbury (OL2162290A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 16, 16, '1953', '63.025.530/0062‑26', 'Simon and Schuster', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9781451673319-L.jpg', '9781451673319', 'Um romance distopico sobre uma sociedade futura onde livros sao banidos e queimados por bombeiros.', 'Fahrenheit 451'),
                                                                                                                                                                 (false, 16, 16, '1962', '63.025.530/0062‑26', 'Simon and Schuster', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9781451678192-L.jpg', '9781451678192', 'Uma colecao de historias interligadas sobre a colonizacao de Marte por humanos fugindo da Terra.', 'Cronicas Marcianas');

-- Harper Lee (OL26321A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 4, 4, '1960', '63.025.530/0062‑26', 'Harper Perennial', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg', '9780061120084', 'Scout Finch narra sua infancia no Alabama enquanto seu pai defende um homem negro acusado de estupro.', 'O Sol e Para Todos'),
                                                                                                                                                                 (false, 4, 4, '2015', '63.025.530/0062‑26', 'Harper Perennial', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780062409850-L.jpg', '9780062409850', 'Uma Scout adulta retorna a Maycomb para visitar seu pai e confronta as complexidades de seu passado.', 'Va, Coloque um Vigia');

-- Toni Morrison (OL139436A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 13, 13, '1987', '63.025.530/0062‑26', 'Vintage Books', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9781400033416-L.jpg', '9781400033416', 'Uma historia assombrosa sobre Sethe, uma escrava fugitiva assombrada pelo fantasma de sua filha morta.', 'Amada'),
                                                                                                                                                                 (false, 13, 13, '1970', '63.025.530/0062‑26', 'Vintage Books', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9781400033423-L.jpg', '9781400033423', 'A historia de Pecola Breedlove, uma jovem negra que deseja ter olhos azuis na America dos anos 1940.', 'O Olho Mais Azul');

-- William Golding (OL34186A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 4, 4, '1954', '63.025.530/0062‑26', 'Penguin Books', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780399501487-L.jpg', '9780399501487', 'Meninos britanicos presos em uma ilha descendem a selvageria, explorando a escuridao da natureza humana.', 'O Senhor das Moscas'),
                                                                                                                                                                 (false, 4, 4, '1956', '63.025.530/0062‑26', 'Penguin Books', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780156027809-L.jpg', '9780156027809', 'Um homem evolui alem da humanidade moderna apos uma guerra nuclear, lutando para encontrar seu lugar.', 'Os Herdeiros');

-- William Shakespeare (OL2162300A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 1, 1, '1603', '63.025.530/0062‑26', 'Folger Shakespeare', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780743477123-L.jpg', '9780743477123', 'O conto tragico do Principe da Dinamarca buscando vinganca pelo assassinato de seu pai.', 'Hamlet'),
                                                                                                                                                                 (false, 4, 4, '1595', '63.025.530/0062‑26', 'Folger Shakespeare', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780743477116-L.jpg', '9780743477116', 'Dois jovens amantes de familias rivais encontram um destino tragico em Verona.', 'Romeu e Julieta'),
                                                                                                                                                                 (false, 4, 4, '1606', '63.025.530/0062‑26', 'Folger Shakespeare', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780743477109-L.jpg', '9780743477109', 'A ambicao de um general escoces o leva por um caminho sombrio de assassinato e loucura.', 'Macbeth');

-- J.K. Rowling (OL26322A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 30, 30, '1997', '63.025.530/0062‑26', 'Scholastic', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780439708180-L.jpg', '9780439708180', 'Um jovem bruxo descobre sua heranca magica e frequenta a Escola de Magia e Bruxaria de Hogwarts.', 'Harry Potter e a Pedra Filosofal'),
                                                                                                                                                                 (false, 30, 30, '1999', '63.025.530/0062‑26', 'Scholastic', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780439064873-L.jpg', '9780439064873', 'Harry retorna a Hogwarts para seu terceiro ano e aprende sobre um perigoso prisioneiro fugitivo.', 'Harry Potter e o Prisioneiro de Azkaban');

-- Stieg Larsson (OL139437A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 12, 12, '2005', '63.025.530/0062‑26', 'Vintage Books', 'SWEDISH', 'https://covers.openlibrary.org/b/isbn/9780307454546-L.jpg', '9780307454546', 'O jornalista Mikael Blomkvist e a hacker Lisbeth Salander investigam os segredos sombrios de uma familia rica.', 'Os Homens Que Nao Amavam as Mulheres'),
                                                                                                                                                                 (false, 12, 12, '2006', '63.025.530/0062‑26', 'Vintage Books', 'SWEDISH', 'https://covers.openlibrary.org/b/isbn/9780307454553-L.jpg', '9780307454553', 'Lisbeth se torna alvo de investigacao apos assassinatos ligados a sua pesquisa.', 'A Menina Que Brincava com Fogo');

-- Albert Camus (OL34187A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 14, 14, '1942', '63.025.530/0062‑26', 'Vintage Books', 'FRENCH', 'https://covers.openlibrary.org/b/isbn/9780679720201-L.jpg', '9780679720201', 'Meursault, um argelino emocionalmente distante, comete assassinato e enfrenta julgamento, explorando o absurdismo.', 'O Estrangeiro'),
                                                                                                                                                                 (false, 11, 11, '1947', '63.025.530/0062‑26', 'Vintage Books', 'FRENCH', 'https://covers.openlibrary.org/b/isbn/9780679720218-L.jpg', '9780679720218', 'Um romance alegorico sobre uma praga que varre a cidade argelina de Ora.', 'A Peste');

-- Dante Alighieri (OL2162310A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 13, 13, '1320', '63.025.530/0062‑26', 'Penguin Classics', 'ITALIAN', 'https://covers.openlibrary.org/b/isbn/9780142437223-L.jpg', '9780142437223', 'A jornada epica de Dante atraves do Inferno, guiado pelo poeta Virgilio, encontrando pecadores e seus castigos.', 'Inferno'),
                                                                                                                                                                 (false, 13, 13, '1320', '63.025.530/0062‑26', 'Penguin Classics', 'ITALIAN', 'https://covers.openlibrary.org/b/isbn/9780142437247-L.jpg', '9780142437247', 'Dante ascende o Monte Purgatorio, testemunhando almas expiando seus pecados antes de entrar no Paraiso.', 'Purgatorio');

-- Herman Melville (OL26323A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 12, 12, '1851', '63.025.530/0062‑26', 'Penguin Classics', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780142437247-L.jpg', '9780143105954', 'A busca obsessiva do Capitao Ahab para cacar a baleia branca que o mutilou, narrada por Ismael.', 'Moby Dick'),
                                                                                                                                                                 (false, 12, 12, '1853', '63.025.530/0062‑26', 'Penguin Classics', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780486264738-L.jpg', '9780486264738', 'Um escriturario trabalhando em Wall Street gradualmente se recusa a executar suas funcoes com a frase Preferiria nao.', 'Bartleby, o Escrivao');

-- Paulo Coelho (OL2162320A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 25, 25, '1988', '63.025.530/0062‑26', 'HarperOne', 'PORTUGUESE_BRAZILIAN', 'https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg', '9780062315007', 'Santiago, um pastor andaluz, viaja para o Egito seguindo seus sonhos de encontrar um tesouro.', 'O Alquimista'),
                                                                                                                                                                 (false, 20, 20, '1994', '63.025.530/0062‑26', 'HarperOne', 'PORTUGUESE_BRAZILIAN', 'https://covers.openlibrary.org/b/isbn/9780061122415-L.jpg', '9780061122415', 'Pilar e um amigo de infancia se reencontram em uma peregrinacao, explorando amor e espiritualidade.', 'Na Margem do Rio Piedra Eu Sentei e Chorei');

-- Charlotte Brontë (OL139438A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 16, 16, '1847', '63.025.530/0062‑26', 'Penguin Classics', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg', '9780141441146', 'Uma governanta orfa se apaixona por seu empregador, Sr. Rochester, descobrindo segredos sombrios em Thornfield Hall.', 'Jane Eyre'),
                                                                                                                                                                 (false, 11, 11, '1849', '63.025.530/0062‑26', 'Penguin Classics', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780199536658-L.jpg', '9780199536658', 'Uma jovem mulher luta para se estabelecer como professora na Belgica enquanto lida com amor nao correspondido.', 'Villette');

-- Mark Twain (OL34188A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 18, 18, '1884', '63.025.530/0062‑26', 'Penguin Classics', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780143107323-L.jpg', '9780143107323', 'Huck Finn escapa de seu pai abusivo e desce o Mississippi em uma jangada com Jim, um escravo fugitivo.', 'As Aventuras de Huckleberry Finn'),
                                                                                                                                                                 (false, 18, 18, '1876', '63.025.530/0062‑26', 'Penguin Classics', 'ENGLISH', 'https://covers.openlibrary.org/b/isbn/9780143039563-L.jpg', '9780143039563', 'As aventuras de Tom Sawyer em St. Petersburg, Missouri, incluindo testemunhar um assassinato e encontrar um tesouro.', 'As Aventuras de Tom Sawyer');

-- Johann Wolfgang von Goethe (OL2162330A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 11, 11, '1774', '63.025.530/0062‑26', 'Penguin Classics', 'GERMAN', 'https://covers.openlibrary.org/b/isbn/9780143106951-L.jpg', '9780143106951', 'Um romance epistolar sobre o amor apaixonado e tragico de um jovem artista por Charlotte.', 'Os Sofrimentos do Jovem Werther'),
                                                                                                                                                                 (false, 9, 9, '1808', '63.025.530/0062‑26', 'Penguin Classics', 'GERMAN', 'https://covers.openlibrary.org/b/isbn/9780140449013-L.jpg', '9780140449013', 'O conto lendario de um estudioso que faz um pacto com o diabo Mefistofeles em troca de conhecimento.', 'Fausto');

-- Leo Tolstoy (OL26324A)
INSERT INTO livro (deleted, disponiveis, quantidade, ano_publicacao, fk_biblioteca_cnpj, fk_editora_razao_social, idioma, imagem_url, isbn, sinopse, titulo) VALUES
                                                                                                                                                                 (false, 18, 18, '1869', '63.025.530/0062‑26', 'Penguin Classics', 'RUSSIAN', 'https://covers.openlibrary.org/b/isbn/9780143035008-L.jpg', '9780143035008', 'Um romance epico seguindo cinco familias aristocraticas durante as Guerras Napoleonicas na Russia.', 'Guerra e Paz'),
                                                                                                                                                                 (false, 16, 16, '1877', '63.025.530/0062‑26', 'Penguin Classics', 'RUSSIAN', 'https://covers.openlibrary.org/b/isbn/9780143035002-L.jpg', '9780143035002', 'O caso tragico de Anna com o Conde Vronsky e suas consequencias devastadoras na alta sociedade russa.', 'Anna Karenina');